class_name CrewRosterManager
extends RefCounted

## Loads and saves the crew roster — the pool every roguelite crew member is
## drawn from. The shipped roster lives at res://data/crew_roster.json
## (generated by tools/generate_crew_roster.gd); players override it wholesale
## with user://crew_roster.json, edited through the Crew Manager screen.
##
## Entries are validated and backfilled per entry, never rejected as a file:
## a hand-edited override with a few bad rows still loads everything usable.
## Loads are fresh from disk on every call — the file is small and the Crew
## Manager can change it mid-session.

const SHIPPED_PATH := "res://data/crew_roster.json"
const USER_PATH := "user://crew_roster.json"
const ROSTER_VERSION := 1
const DEFAULT_SKILL := 0.5

## Roster entry shape: {id: String, callsign: String, roles: Array[String]
## (snake_case CrewData.ROLE_NAMES values, >= 1 entry, first is the
## default/primary role), skills: {CrewData.SKILL_NAMES -> 0..1}}.


## The active roster: the user override when it exists and yields at least
## one valid entry, otherwise the shipped roster.
static func load_roster() -> Array:
	if FileAccess.file_exists(USER_PATH):
		var user_entries := _validate_entries(_read_entries(USER_PATH))
		if not user_entries.is_empty():
			return user_entries
	return _validate_entries(_read_entries(SHIPPED_PATH))


## Full-replace write of the user override.
static func save_roster(entries: Array) -> bool:
	var payload := {"version": ROSTER_VERSION, "entries": entries}
	var file := FileAccess.open(USER_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Failed to open file for writing: " + USER_PATH)
		return false
	file.store_string(JSON.stringify(payload, "\t"))
	file.close()
	return true


## Drop the user override so the shipped roster applies again.
static func reset_to_defaults() -> void:
	if FileAccess.file_exists(USER_PATH):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(USER_PATH))


static func has_user_override() -> bool:
	return FileAccess.file_exists(USER_PATH)


## The hiring pool: roster entries not yet consumed this run, optionally
## filtered to candidates qualified for one role. Pure given its inputs.
static func available_entries(hired_ids: Array, role: int = -1) -> Array:
	var role_name: String = CrewData.role_to_name(role) if role >= 0 else ""
	var available: Array = []
	for entry in load_roster():
		if hired_ids.has(entry.id):
			continue
		if role_name != "" and not entry.roles.has(role_name):
			continue
		available.append(entry)
	return available


## Find one roster entry by id; {} when absent (or consumed ids removed by a
## mid-run override edit).
static func entry_by_id(roster_id: String) -> Dictionary:
	for entry in load_roster():
		if entry.id == roster_id:
			return entry
	return {}


static func _read_entries(path: String) -> Array:
	if not FileAccess.file_exists(path):
		push_error("Crew roster file missing: " + path)
		return []
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		push_error("Failed to open file for reading: " + path)
		return []
	var json_string := file.get_as_text()
	file.close()

	var json := JSON.new()
	if json.parse(json_string) != OK:
		push_error("Failed to parse crew roster JSON (%s): %s" % [path, json.get_error_message()])
		return []
	var data = json.get_data()
	if data is Dictionary and data.get("entries") is Array:
		return data.entries
	return []


## Per-entry validation and backfill. Drops what cannot be repaired (no id),
## fixes everything else: unknown role names become pilot, an empty roles
## array backfills to [pilot], missing callsigns come from the id, skills
## are completed and clamped into 0..1.
static func _validate_entries(raw: Array) -> Array:
	var validated: Array = []
	var seen_ids := {}
	for item in raw:
		if not item is Dictionary:
			continue
		var entry: Dictionary = item
		var id := str(entry.get("id", ""))
		if id == "" or seen_ids.has(id):
			continue
		seen_ids[id] = true

		var role_names := _validated_role_names(entry)
		var callsign := str(entry.get("callsign", ""))
		if callsign == "":
			callsign = id.capitalize()

		var raw_skills: Dictionary = entry.get("skills", {}) if entry.get("skills") is Dictionary else {}
		var skills := {}
		for skill_name in CrewData.SKILL_NAMES:
			skills[skill_name] = clampf(float(raw_skills.get(skill_name, DEFAULT_SKILL)), 0.0, 1.0)

		validated.append({"id": id, "callsign": callsign, "roles": role_names, "skills": skills})
	return validated


## The entry's qualified role names, resolved through the canonical Role
## round-trip so every name is a known ROLE_NAMES value, deduplicated
## (qualified_roles_from_entry dedupes) and never empty.
static func _validated_role_names(entry: Dictionary) -> Array:
	var role_names: Array = []
	for role in CrewData.qualified_roles_from_entry(entry):
		role_names.append(CrewData.role_to_name(role))
	return role_names
